In [1]:
# Importação das bibliotecas que utilizaremos
import pandas as pd
import math

In [2]:
# Importação do arquivo de tabela a ser utilizado, através do path na seção "Files" do Colab, contendo as informações de resíduos sólidos
file='./Solid_waste_pt.xlsx'

In [3]:
# Visão geral da tabela
df=pd.read_excel(file)
df

,Regiao_Coleta,Tipo_Residuo,Origem_Residuo,Metodo_Destinacao,Massa_Coletada_kg,Densidade_Residuo_kgm3,Umidade_Residuo_pct,Distancia_Destinacao_km,Custo_Coleta_Transporte_RS_ton,Indice_Reciclabilidade_pct,Poder_Calorifico_MJkg
0,Zona Norte,Reciclável,Comercial,Compostagem,542.4,50.7,11.5,10.6,167.0,98.0,19.2
1,Zona Oeste,Orgânico,Residencial,Compostagem,223.1,321.1,81.6,8.6,140.2,0.0,8.1
2,Zona Leste,Orgânico,Residencial,Aterro Sanitário,356.3,341.2,77.6,18.0,184.2,10.1,3.6
3,Zona Leste,Orgânico,Residencial,Aterro Sanitário,275.9,371.8,77.0,17.2,178.8,5.2,6.5
4,Centro,Orgânico,Industrial,Reciclagem,942.3,367.1,76.6,11.7,126.8,7.0,4.2
...,...,...,...,...,...,...,...,...,...,...,...
289,Zona Oeste,Orgânico,Comercial,Aterro Sanitário,680.6,355.4,57.1,7.9,137.9,1.3,1.0
290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,Varíaveis qualitativas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,Varíaveis quantitativas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Tabela que mostra a quantidade de coletas realizadas em cada regiao
df_Umidade_Residuo_pct=df.Umidade_Residuo_pct.value_counts()
df_Umidade_Residuo_pct

Umidade_Residuo_pct
2.0     18
16.0     4
32.3     4
16.8     3
60.7     3
        ..
13.9     1
6.3      1
12.0     1
9.1      1
2.7      1
Name: count, Length: 222, dtype: int64

In [5]:
# Ordenação da tabela em ordem alfabética
df_Umidade_Residuo_pct=df.Umidade_Residuo_pct.value_counts().sort_index()
df_Umidade_Residuo_pct

Umidade_Residuo_pct
2.0     18
2.1      1
2.7      1
3.0      1
3.2      1
        ..
77.0     1
77.2     1
77.6     1
78.5     1
81.6     1
Name: count, Length: 222, dtype: int64

In [7]:
# Impressão do total das coletas realizadas
total_df_Umidade_Residuo_pct=df_Umidade_Residuo_pct.sum()
total_df_Umidade_Residuo_pct

np.int64(290)